/**
 * lib/db/auth.ts — the SQL behind activation, passkeys and sessions.
 *
 * Lives in `lib/db/` because that is the only place SQL exists (C6). The
 * ceremony logic — challenges, origin checks, signature verification — is in
 * `lib/auth/passkey.ts`, which never touches the database directly.
 *
 * These functions do NOT take an `AuthContext`, and that is deliberate: they run
 * BEFORE anybody has an identity. They are the one exception to the required-ctx
 * rule, so each one is written defensively and every export is listed here:
 *
 *   findProfileByPhone · createActivationChallenge · consumeActivationChallenge
 *   listCredentialsForLogin · saveCredential · updateSignCount
 *   putWebAuthnChallenge · takeWebAuthnChallenge · openSession · issueRecoveryCodes
 *
 * Nothing here returns anything a caller could use to enumerate residents.
 */

import type { Db } from './driver.js';
import { newId, mutate, type Clock } from './index.js';
import type { AuthContext, Role } from '../../types/domain.js';

const TOKEN_TTL_HOURS = 24;
const CHALLENGE_TTL_SECONDS = 300;

function plus(now: string, seconds: number): string {
  return new Date(Date.parse(now) + seconds * 1000).toISOString().replace(/\.\d+Z$/, 'Z');
}

/* ===================================================================== */
/* Activation — the board-issued one-time link (ADR-016)                 */
/* ===================================================================== */

/**
 * Resolve a phone number to a person, for login.
 *
 * ⚠️ Returns `null` for unknown, inactive AND non-current numbers alike. The
 * CALLER must not branch visibly on the difference: 03_RBAC §5 requires the same
 * response whether or not a number is registered, so an outsider cannot harvest
 * which numbers belong to the compound.
 */
export async function findProfileByPhone(db: Db, phoneE164: string) {
  return db.prepare(
    `SELECT p.id, p.full_name, p.role, p.is_active
       FROM phone_identifiers pi
       JOIN profiles p ON p.id = pi.profile_id
      WHERE pi.phone_e164 = ? AND pi.status = 'active' AND p.is_active = 1`
  ).bind(phoneE164).first<{ id: string; full_name: string; role: Role; is_active: number }>();
}

/**
 * Issue a single-use activation token. The plaintext is returned ONCE, to be
 * handed to a board member; only its hash is stored. One live challenge per
 * person (`idx_activation_one_live`), so issuing a new link invalidates the old.
 */
export async function createActivationChallenge(
  ctx: AuthContext, db: Db, profileId: string, tokenHash: string,
  purpose: 'first_activation' | 'recovery' | 'new_device', now: Clock,
): Promise<void> {
  await mutate(db, ctx,
    { action: 'activation.issue', table: 'activation_challenges', entityId: profileId,
      after: { purpose, channel: 'board_link' } },
    // supersede any live challenge first — otherwise the partial unique index
    // rejects the insert and a board member cannot re-send a lost link
    db.prepare(`UPDATE activation_challenges SET consumed_at = ?
                 WHERE profile_id = ? AND consumed_at IS NULL`).bind(now(), profileId),
    db.prepare(
      `INSERT INTO activation_challenges (id, profile_id, token_hash, purpose, channel,
         issued_by, expires_at) VALUES (?,?,?,?, 'board_link', ?, ?)`
    ).bind(newId('ACT'), profileId, tokenHash, purpose, ctx.personId,
           plus(now(), TOKEN_TTL_HOURS * 3600)),
  );
}

/**
 * Burn an activation token and return whose it was. Single-use is enforced by a
 * conditional UPDATE, so two simultaneous clicks on a forwarded link cannot both
 * succeed — the second changes zero rows.
 */
export async function consumeActivationChallenge(
  db: Db, tokenHash: string, now: Clock,
): Promise<{ profileId: string; fullName: string; purpose: string } | null> {
  const row = await db.prepare(
    `SELECT ac.id, ac.profile_id, ac.purpose, p.full_name
       FROM activation_challenges ac JOIN profiles p ON p.id = ac.profile_id
      WHERE ac.token_hash = ? AND ac.consumed_at IS NULL AND ac.expires_at > ?
        AND p.is_active = 1`
  ).bind(tokenHash, now()).first<{ id: string; profile_id: string; purpose: string; full_name: string }>();
  if (!row) return null;

  const burned = await db.prepare(
    `UPDATE activation_challenges SET consumed_at = ? WHERE id = ? AND consumed_at IS NULL`
  ).bind(now(), row.id).run();
  if (burned.meta.changes !== 1) return null;   // lost the race; treat as invalid

  return { profileId: row.profile_id, fullName: row.full_name, purpose: row.purpose };
}

/* ===================================================================== */
/* WebAuthn challenges — server-side, single-use, short-lived            */
/* ===================================================================== */

/**
 * A WebAuthn challenge must be generated by US, stored, and accepted exactly
 * once. Kept in D1 rather than KV: an unauthenticated caller can trigger this
 * write, and KV allows 1,000 writes/day against D1's 100,000 (ADR-017).
 */
export async function putWebAuthnChallenge(
  db: Db, key: string, challenge: string, profileId: string | null, now: Clock,
): Promise<void> {
  await db.prepare(
    `INSERT INTO webauthn_challenges (id, challenge_key, challenge, profile_id, expires_at)
     VALUES (?,?,?,?,?)`
  ).bind(newId('WAC'), key, challenge, profileId, plus(now(), CHALLENGE_TTL_SECONDS)).run();
}

/** Take-and-burn. A replayed challenge finds nothing. */
export async function takeWebAuthnChallenge(
  db: Db, key: string, now: Clock,
): Promise<{ challenge: string; profileId: string | null } | null> {
  const row = await db.prepare(
    `SELECT id, challenge, profile_id FROM webauthn_challenges
      WHERE challenge_key = ? AND consumed_at IS NULL AND expires_at > ?`
  ).bind(key, now()).first<{ id: string; challenge: string; profile_id: string | null }>();
  if (!row) return null;
  const burned = await db.prepare(
    `UPDATE webauthn_challenges SET consumed_at = ? WHERE id = ? AND consumed_at IS NULL`
  ).bind(now(), row.id).run();
  if (burned.meta.changes !== 1) return null;
  return { challenge: row.challenge, profileId: row.profile_id };
}

/* ===================================================================== */
/* Credentials                                                           */
/* ===================================================================== */

export interface StoredCredential {
  id: string; credential_id: string; public_key: Uint8Array;
  sign_count: number; transports: string | null; rp_id: string;
}

/** Live credentials for a person, for the `allowCredentials` list. */
export async function listCredentialsForLogin(db: Db, profileId: string) {
  const r = await db.prepare(
    `SELECT id, credential_id, public_key, sign_count, transports, rp_id
       FROM passkeys WHERE profile_id = ? AND revoked_at IS NULL`
  ).bind(profileId).all<StoredCredential>();
  return r.results;
}

export async function getCredential(db: Db, credentialId: string) {
  return db.prepare(
    `SELECT pk.id, pk.credential_id, pk.public_key, pk.sign_count, pk.transports, pk.rp_id,
            pk.profile_id, p.role, p.is_active
       FROM passkeys pk JOIN profiles p ON p.id = pk.profile_id
      WHERE pk.credential_id = ? AND pk.revoked_at IS NULL`
  ).bind(credentialId).first<StoredCredential & { profile_id: string; role: Role; is_active: number }>();
}

export async function saveCredential(
  db: Db, profileId: string, c: {
    credentialId: string; publicKey: Uint8Array; signCount: number;
    transports: string[] | null; rpId: string; deviceLabelAr: string;
  },
): Promise<void> {
  await db.prepare(
    `INSERT INTO passkeys (id, profile_id, credential_id, public_key, sign_count,
       transports, rp_id, device_label_ar) VALUES (?,?,?,?,?,?,?,?)`
  ).bind(newId('PSK'), profileId, c.credentialId, c.publicKey, c.signCount,
         c.transports ? JSON.stringify(c.transports) : null, c.rpId, c.deviceLabelAr).run();
  await db.prepare(
    `INSERT INTO audit_log (id, actor_id, actor_role, action, entity_table, entity_id, after_json)
     VALUES (?,?,?, 'passkey.enroll', 'passkeys', ?, ?)`
  ).bind(newId('AUD'), profileId, null, profileId,
         JSON.stringify({ rpId: c.rpId, label: c.deviceLabelAr })).run();
}

/**
 * Advance the signature counter, and REFUSE to go backwards.
 *
 * A counter that does not increase is how a cloned authenticator is detected —
 * the clone replays a value the real device has already passed. Many platform
 * authenticators (Touch ID, Android) legitimately always report 0, so the rule
 * is: if either side is 0, counters are unsupported and we skip the check;
 * otherwise the new value MUST exceed the stored one.
 */
export async function updateSignCount(
  db: Db, credentialId: string, newCount: number, storedCount: number, now: Clock,
): Promise<'ok' | 'cloned'> {
  if (storedCount > 0 && newCount > 0 && newCount <= storedCount) return 'cloned';
  await db.prepare(
    `UPDATE passkeys SET sign_count = ?, last_used_at = ? WHERE credential_id = ?`
  ).bind(Math.max(newCount, storedCount), now(), credentialId).run();
  return 'ok';
}

export async function revokeCredential(
  ctx: AuthContext, db: Db, passkeyId: string, now: Clock,
): Promise<void> {
  await mutate(db, ctx,
    { action: 'passkey.revoke', table: 'passkeys', entityId: passkeyId },
    db.prepare(`UPDATE passkeys SET revoked_at = ?, revoked_by = ?
                 WHERE id = ? AND profile_id = ? AND revoked_at IS NULL`)
      .bind(now(), ctx.personId, passkeyId, ctx.personId),
  );
}

/* ===================================================================== */
/* Sessions                                                              */
/* ===================================================================== */

/**
 * Open a session. One year on a trusted device (ADR-009/011) — deliberate, not
 * lazy: residents visit four times a year, and every avoided login is a step
 * where an elderly user could fail. Any sensitive action re-verifies with the
 * passkey regardless, via `reauth_at`.
 */
export async function openSession(
  db: Db, profileId: string, tokenHash: string, now: Clock,
  meta: { ip?: string; userAgent?: string } = {},
): Promise<string> {
  const id = newId('SES');
  const oneYear = plus(now(), 365 * 24 * 3600);
  await db.prepare(
    `INSERT INTO sessions (id, profile_id, token_hash, expires_at, reauth_at, ip, user_agent)
     VALUES (?,?,?,?,?,?,?)`
  ).bind(id, profileId, tokenHash, oneYear, now(), meta.ip ?? null, meta.userAgent ?? null).run();
  await db.prepare(`UPDATE profiles SET last_login_at = ? WHERE id = ?`).bind(now(), profileId).run();
  await db.prepare(
    `INSERT INTO audit_log (id, actor_id, action, entity_table, entity_id, ip, user_agent)
     VALUES (?,?, 'session.open', 'sessions', ?, ?, ?)`
  ).bind(newId('AUD'), profileId, id, meta.ip ?? null, meta.userAgent ?? null).run();
  return id;
}

/**
 * Issue printed single-use recovery codes (R-023).
 *
 * ⚠️ Issuing a new set **retires the previous one**, in the same batch.
 *
 * The first version appended, and a test caught what that means: every
 * activation, every new device, every recovery handed out six MORE codes and
 * left all the old ones live. After three such events a resident has eighteen
 * valid passkey bypasses on eighteen pieces of paper, in drawers and photos and
 * WhatsApp messages, and neither they nor the board has any idea how many exist.
 *
 * The resident's mental model is "here are my codes" — singular, replacing.
 * The system has to match it.
 */
export async function issueRecoveryCodes(
  db: Db, profileId: string, hashes: string[], now?: Clock,
): Promise<void> {
  const stamp = now ? now() : '1970-01-01T00:00:00Z';
  await db.batch([
    // retire every unused code from any previous set
    db.prepare(`UPDATE recovery_codes SET used_at = ? WHERE profile_id = ? AND used_at IS NULL`)
      .bind(stamp, profileId),
    ...hashes.map(h => db.prepare(
      `INSERT INTO recovery_codes (id, profile_id, code_hash) VALUES (?,?,?)`
    ).bind(newId('RCV'), profileId, h)),
  ]);
}

/**
 * Redeem a printed recovery code (R-023).
 *
 * This is a passkey BYPASS, so it is written as tightly as the thing it
 * bypasses: the code is matched by hash, burned by a conditional UPDATE so two
 * simultaneous attempts cannot both win, and **every existing session is
 * revoked** — if somebody else had the phone, recovery must end their access,
 * not run alongside it.
 *
 * Returns the person only on success. A wrong code is indistinguishable from a
 * code belonging to somebody else.
 */
export async function redeemRecoveryCode(
  db: Db, codeHash: string, now: Clock,
): Promise<{ profileId: string; fullName: string; remaining: number } | null> {
  const row = await db.prepare(
    `SELECT rc.id, rc.profile_id, p.full_name
       FROM recovery_codes rc JOIN profiles p ON p.id = rc.profile_id
      WHERE rc.code_hash = ? AND rc.used_at IS NULL AND p.is_active = 1`
  ).bind(codeHash).first<{ id: string; profile_id: string; full_name: string }>();
  if (!row) return null;

  const burned = await db.prepare(
    `UPDATE recovery_codes SET used_at = ? WHERE id = ? AND used_at IS NULL`
  ).bind(now(), row.id).run();
  if (burned.meta.changes !== 1) return null;      // lost the race

  await db.batch([
    // Recovery means "I lost the device." Anything still holding a session on a
    // device the resident no longer controls must lose it now.
    db.prepare(`UPDATE sessions SET revoked_at = ? WHERE profile_id = ? AND revoked_at IS NULL`)
      .bind(now(), row.profile_id),
    // The old passkeys go too. A recovered account with the lost phone's
    // credential still enrolled has not actually been recovered.
    db.prepare(`UPDATE passkeys SET revoked_at = ? WHERE profile_id = ? AND revoked_at IS NULL`)
      .bind(now(), row.profile_id),
    db.prepare(
      `INSERT INTO audit_log (id, actor_id, action, entity_table, entity_id, after_json)
       VALUES (?,?, 'account.recover', 'recovery_codes', ?, ?)`
    ).bind(newId('AUD'), row.profile_id, row.id,
           JSON.stringify({ method: 'printed_code' })),
  ]);

  const left = await db.prepare(
    `SELECT COUNT(*) n FROM recovery_codes WHERE profile_id = ? AND used_at IS NULL`
  ).bind(row.profile_id).first<{ n: number }>();

  return { profileId: row.profile_id, fullName: row.full_name, remaining: left?.n ?? 0 };
}

/** Rate limiting lives in D1 for the same reason challenges do (ADR-017). */
export async function countRecentAttempts(
  db: Db, scope: string, key: string, sinceIso: string,
): Promise<number> {
  const r = await db.prepare(
    `SELECT COUNT(*) n FROM auth_attempts WHERE scope = ? AND key = ? AND created_at > ?`
  ).bind(scope, key, sinceIso).first<{ n: number }>();
  return r?.n ?? 0;
}

export async function recordAttempt(
  db: Db, scope: string, key: string, ok: boolean, now: Clock,
): Promise<void> {
  await db.prepare(
    `INSERT INTO auth_attempts (id, scope, key, ok, created_at) VALUES (?,?,?,?,?)`
  ).bind(newId('ATT'), scope, key, ok ? 1 : 0, now()).run();
}
