-- ⚠️ IMAGINARY DATA — generated by seed/demo/generate.py, seed 20260804.
-- Every name, amount, phone number and date below is INVENTED (C10).
-- Ids begin with 'DEMO'; migration 0006 refuses them on a production database.
-- Load order: migrations -> seed/prod -> THIS FILE.
-- Before loading, mark the database as a demo database:
--     UPDATE env_guard SET environment='demo', set_by='dev', note='local demo';


-- ------------------------------------------------- opening balance ---
INSERT INTO journal_entries (id, entry_no, entry_date, period_id, description_ar, source_type, source_id, created_by) VALUES ('DEMOJE00000000000000000001','J-2026-000001','2026-01-01','DEMOFPR0000000000000000001','رصيد أول المدة 1 يناير 2026','opening_balance',NULL,'DEMOPRF0000000000000000002');
INSERT INTO journal_lines (id, entry_id, line_no, account_id, fund_id, debit_piastres, credit_piastres, unit_id, memo_ar) VALUES ('DEMOJL00000000000000000001','DEMOJE00000000000000000001',1,'ACC00000000000000000001101','FND00000000000000000000001',4500000,0,NULL,'الخزنة النقدية');
INSERT INTO journal_lines (id, entry_id, line_no, account_id, fund_id, debit_piastres, credit_piastres, unit_id, memo_ar) VALUES ('DEMOJL00000000000000000002','DEMOJE00000000000000000001',2,'ACC00000000000000000001102','FND00000000000000000000001',18200000,0,NULL,'الحساب البنكي');
INSERT INTO journal_lines (id, entry_id, line_no, account_id, fund_id, debit_piastres, credit_piastres, unit_id, memo_ar) VALUES ('DEMOJL00000000000000000003','DEMOJE00000000000000000001',3,'ACC00000000000000000003101','FND00000000000000000000001',0,22700000,NULL,'رصيد مُرحّل من 2025');
UPDATE journal_entries SET approved_by='DEMOPRF0000000000000000003', posted_at='2026-01-01T10:00:00Z' WHERE id='DEMOJE00000000000000000001';
