-- =============================================================================
-- 0007_webauthn.sql — challenge storage and rate limiting for the login path
--
-- Both tables live in D1, not KV, and that is a deliberate architectural choice
-- rather than convenience: an UNAUTHENTICATED caller can trigger a write to
-- both. KV's free tier allows 1,000 writes/day against D1's 100,000 (ADR-014,
-- ADR-017), so one bored attacker hammering /login would exhaust the day's KV
-- budget and take the login path down for the whole village.
-- =============================================================================

PRAGMA foreign_keys = ON;

-- -----------------------------------------------------------------------------
-- webauthn_challenges
-- A WebAuthn challenge must be generated by the server, stored, and accepted
-- exactly once. Accepting a client-supplied challenge, or accepting one twice,
-- removes the entire replay protection the ceremony exists to provide.
-- -----------------------------------------------------------------------------
CREATE TABLE webauthn_challenges (
  id            TEXT NOT NULL PRIMARY KEY CHECK (length(id) = 26),
  -- opaque per-attempt key handed to the browser; NOT the challenge itself
  challenge_key TEXT NOT NULL UNIQUE,
  challenge     TEXT NOT NULL,
  -- NULL during login: we do not yet know (or admit) who is attempting
  profile_id    TEXT REFERENCES profiles(id),
  expires_at    TEXT NOT NULL,
  consumed_at   TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
) STRICT;

CREATE INDEX idx_wac_live ON webauthn_challenges(challenge_key) WHERE consumed_at IS NULL;

-- -----------------------------------------------------------------------------
-- auth_attempts — rate limiting (03_RBAC §4)
-- Recorded for successes as well as failures, so a support conversation can
-- answer "did anyone try to get into my account?" — which is the question a
-- resident actually asks after a phone change.
-- -----------------------------------------------------------------------------
CREATE TABLE auth_attempts (
  id         TEXT    NOT NULL PRIMARY KEY CHECK (length(id) = 26),
  scope      TEXT    NOT NULL CHECK (scope IN ('login_begin','login_finish','activate','recover')),
  -- a phone number, an IP, or a profile id, depending on scope
  key        TEXT    NOT NULL,
  ok         INTEGER NOT NULL CHECK (ok IN (0,1)),
  created_at TEXT    NOT NULL
) STRICT;

CREATE INDEX idx_attempts_lookup ON auth_attempts(scope, key, created_at);
